/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BUSNAME "xyz.openbmc_project.Time.Manager"

#define DEFAULT_TIME_MODE Mode::Manual

#define DEFAULT_TIME_OWNER Owner::Both

#define HOST_OFFSET_FILE "/var/lib/obmc/saved_host_offset"

#define OBJPATH_BMC "/xyz/openbmc_project/time/bmc"

#define OBJPATH_HOST "/xyz/openbmc_project/time/host"

